apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-courses-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-courses-api
  template:
    metadata:
      labels:
        app: nodejs-courses-api
    spec:
      containers:
        - name: postgresql-server-api-container
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: "HDLCrin8*"
            - name: POSTGRES_DATABASE
              value: "courses_db"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-server-pvolume
              mountPath: /var/lib/postgresql/data
        - name: nodejs-courses-api-container
          image: jcortizs/nodejs_courses_api
          env:
            - name: POSTGRES_HOST
              value: "localhost"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USERNAME
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "HDLCrin8*"
            - name: POSTGRES_DATABASE
              value: "courses_db"
          ports:
            - containerPort: 8090
      volumes:
        - name: postgresql-server-pvolume
          persistentVolumeClaim:
            claimName: postgresql-server-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-courses-api-service
spec:
  selector:
    app: nodejs-courses-api
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer
